langulage: go

services:
  - docker

env:
  - POSTGRES_USER=postgres POSTGRES_PASSWORD=postgres

before_install:
  - docker pull golangci/golangci-lint
  - docker pull postgres:13
  - docker pull septemhill/liquibase:latest
  - docker run -v /home/travis/gopath/src/github.com/septemhill/test:/app -w /app golangci/golangci-lint golangci-lint run
  - docker run -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres
  - docker run --net=host -v /home/travis/gopath/src/github.com/septemhill/test/migration:/liquibase/changelog septemhill/liquibase --logLevel=debug --url=jdbc:postgresql://localhost:5432/postgres --changeLogFile=./changelog/dbchangelog.xml --username=postgres --password=postgres update

sudo: true

gobuild_args: -v

go:
  - "1.14.7"
  - "1.15.1"
  - master

notifications:
  slack: obsamworkspace:CkAsaDCf4HavBESkjLhHw33W
#jobs:
#  include:
#    - stage: Show me current path now
#      script: echo $(PWD)
#    - stage: Build project
#      script: go build -v
#    - stage: Run test cases
#      script: go test $(gobuild_args) ./...
